config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  get 'items/get'
  post 'items/get'
  get 'items/download'
  post 'items/download'
  get 'items' => 'items#show'
  get 'items/show'
  post 'items/show'
  get 'items/delete'
  post 'items/load'
  post 'items/update'

  post 'items/save'
  patch 'items/save'
  get 'items/save' => 'items#show'

  get 'items/search'
  post 'items/search'

  root to: 'apps#show'
  get 'apps/show'
  post 'stocks/delete'
  get 'stocks/show'
  post 'stocks/show'
  post 'stocks/update'
  get 'stocks/search'
  post 'stocks/search'
  post 'stocks/import'
  get 'stocks/export'
  post 'stocks/export'
  post 'stocks/load'
  post 'stocks/setpw'
  get 'stocks/export.csv'  => 'stocks#show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, at: "/resque"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'nokogiri'
  require 'open-uri'
  require 'typhoeus'
  require 'uri'
  require 'cgi'
  require 'rexml/document'

  def download
    @user = current_user.email
    if request.post? then
      respond_to do |format|
        @item_id = params[:item_id]
        @title = params[:title]
        @item_url = params[:item_url]
        @price = params[:price]
        @condition = params[:condition]
        @ship = params[:shipping]
        @specs = params[:specs]

        @search_group = SearchGroup.where(user: @user)
        @products = nil

        if @search_group.length > 0 then
          @search_group = @search_group.order('created_at DESC').first
          @group_id = @search_group.group_id
          logger.debug(@group_id)
          @products = Product.where(user: @user, group_id: @group_id)
        else
          @search_group = nil
        end
        format.csv {send_data render_to_string, filename: "ebay検索結果_#{Time.zone.now.strftime("%Y%m%d%H%M%S")}.csv", type: :csv}
      # redirect_to '/items/get#tab_c'
      end
    end
  end

  def get

    @user = current_user.email

    @group_id = nil
    @search_group = SearchGroup.where(user: @user)
    @products = nil

    if @search_group.length > 0 then
      @search_group = @search_group.order('created_at DESC').first
      @group_id = @search_group.group_id
      logger.debug(@group_id)
      @status = @search_group.status
      @products = Product.where(user: @user, group_id: @group_id)
    else
      @search_group = nil
      @status = "実行前"
    end

    @search_user = @user + "_detail"
    @condition = SearchCondition.find_or_create_by(user: @search_user)

    @search_keyword = params[:search_keyword]

    @sales_group = {
      '0: All': 'All',
      '1: Auction': 'Auction',
      '2: Auction with BIN': 'AuctionWithBIN',
      '3: Fixed Price (Buy It Now)': 'FixedPrice'
    }

    @condition_group = {
      '0: All': 1,
      '1: New': 1000,
      '2: Used': 3000
    }

    @category_group = {
      '0: All': -1,
      '1: Jewelry & Watches': 281,
      '2: Antiques': 20081,
      '3: Art': 550,
      '4: Cameras & Photo': 625,
      '5: Business & Industrial': 12576,
      '6: Books': 267,
      '7: Baby': 2984,
      '8: Cell Phones & PDAs': 15032,
      '9: Clothing, Shoes & Accessories': 11450,
      '10: Coins & Paper Money': 11116,
      '11: Collectibles': 1,
      '12: Computers & Networking': 58058,
      '13: Crafts': 14339,
      '14: Dolls & Bears': 237,
      '15: DVDs & Movies': 11232,
      '16: Electronics': 293,
      '17: Entertainment Memorabilia': 45100,
      '18: Gift Certificates': 31411,
      '19: Health & Beauty': 26395,
      '20: Home & Garden': 11700,
      '21: Music': 11233,
      '22: Musical Instruments': 619,
      '23: Pet Supplies': 1281,
      '24: Pottery & Glass': 870,
      '25: Sporting Goods': 382,
      '26: Sports Mem, Cards & Fan Shop': 64482,
      '27: Tickets': 1305,
      '28: Toys & Hobbies': 220,
      '29: Video Games': 1249
    }

    if request.post? then
      ProductSearchJob.perform_later(@search_keyword, @user)
      redirect_to '/items/get#tab_c'
    end

  end

  def show
    gon.keylist = Item.all
    @user = current_user.email
    @item = Item.find_by(user: current_user.email)
    @condition = SearchCondition.find_by(user: current_user.email)
    @sales_group = {
      '0: All': 'All',
      '1: Auction': 'Auction',
      '2: Auction with BIN': 'AuctionWithBIN',
      '3: Fixed Price (Buy It Now)': 'FixedPrice'
    }

    @condition_group = {
      '0: All': 1,
      '1: New': 1000,
      '2: Used': 3000
    }

    @category_group = {
      '0: All': -1,
      '1: Jewelry & Watches': 281,
      '2: Antiques': 20081,
      '3: Art': 550,
      '4: Cameras & Photo': 625,
      '5: Business & Industrial': 12576,
      '6: Books': 267,
      '7: Baby': 2984,
      '8: Cell Phones & PDAs': 15032,
      '9: Clothing, Shoes & Accessories': 11450,
      '10: Coins & Paper Money': 11116,
      '11: Collectibles': 1,
      '12: Computers & Networking': 58058,
      '13: Crafts': 14339,
      '14: Dolls & Bears': 237,
      '15: DVDs & Movies': 11232,
      '16: Electronics': 293,
      '17: Entertainment Memorabilia': 45100,
      '18: Gift Certificates': 31411,
      '19: Health & Beauty': 26395,
      '20: Home & Garden': 11700,
      '21: Music': 11233,
      '22: Musical Instruments': 619,
      '23: Pet Supplies': 1281,
      '24: Pottery & Glass': 870,
      '25: Sporting Goods': 382,
      '26: Sports Mem, Cards & Fan Shop': 64482,
      '27: Tickets': 1305,
      '28: Toys & Hobbies': 220,
      '29: Video Games': 1249
    }

    if @item == nil then
      @item = Item.new
    end

    logger.debug(@condition)
    if @condition == nil then
      logger.debug("User is not found")
      @condition = SearchCondition.new
    end
  end

  def search
    if request.post? then
      res = JSON.parse(params[:data])
      query = res[0]

      #検索条件の反映
      cuser = SearchCondition.find_by(user:current_user.email)
      appid = cuser.app_id
      cat = cuser.category_id
      lp = cuser.low_price
      hp = cuser.high_price
      cond = cuser.item_condition
      sale = cuser.sales_type
      rank = cuser.rank
      score = cuser.score
      handling_time = cuser.handling_time

      itemfilter = ""
      if sale == "All" then
        itemfiler = "&itemFilter(0).name=ListingType"\
                  + "&itemFilter(0).value(0)=FixedPrice"\
                  + "&itemFilter(0).value(1)=AuctionWithBIN"\
                  + "&itemFilter(0).value(2)=Auction"
      else
        itemfiler = "&itemFilter(0).name=ListingType"\
                  + "&itemFilter(0).value(0)=" + sale
      end

      if cond == "1" then
        itemfiler = itemfiler + "&itemFilter(1).name=Condition"\
                  + "&itemFilter(1).value(0)=1000"\
                  + "&itemFilter(1).value(1)=3000"\

      else
        itemfiler = itemfiler + "&itemFilter(1).name=Condition"\
                  + "&itemFilter(1).value(0)=" + cond
      end
      fnum = 2
      if score != nil then
        itemfiler = itemfiler + "&itemFilter(2).name=FeedbackScoreMin"\
                  + "&itemFilter(2).value(0)=" + score
        fnum = fnum + 1
      end

      if handling_time != nil then
        itemfiler = itemfiler + "&itemFilter(3).name=MaxHandlingTime"\
                  + "&itemFilter(3).value(0)=" + handling_time.to_i.to_s
        fnum = fnum + 1
      end

      if lp != nil then
        itemfiler = itemfiler + "&itemFilter(" + fnum.to_s + ").name=MinPrice"\
                  + "&itemFilter(" + fnum.to_s + ").value(0)=" + lp.to_s
        fnum = fnum + 1
      end

      if hp != nil then
        itemfiler = itemfiler + "&itemFilter(" + fnum.to_s + ").name=MaxPrice"\
                  + "&itemFilter(" + fnum.to_s + ").value(0)=" + hp.to_s
        fnum = fnum + 1
      end

      if cat == "-1" then
        endpoint  = "https://svcs.ebay.com/services/search/FindingService/v1?"\
                  + "OPERATION-NAME=findItemsAdvanced"\
                  + "&SECURITY-APPNAME=" + appid \
                  + "&RESPONSE-DATA-FORMAT=XML"\
                  + "&REST-PAYLOAD"\
                  + itemfiler\
                  + "&sortOrder=PricePlusShippingLowest"\
                  + "&keywords=" + URI.escape(query[1].encode("Shift_JIS")).gsub("+","%20")
      else
        endpoint  = "https://svcs.ebay.com/services/search/FindingService/v1?"\
                  + "OPERATION-NAME=findItemsAdvanced"\
                  + "&SECURITY-APPNAME=" + appid \
                  + "&RESPONSE-DATA-FORMAT=XML"\
                  + "&REST-PAYLOAD"\
                  + "&sortOrder=PricePlusShippingLowest"\
                  + itemfiler\
                  + "&categoryId=" + cat\
                  + "&keywords=" + URI.escape(query[1].encode("Shift_JIS")).gsub("+","%20")
      end

      charset = nil

      logger.debug("------------ Endpoint ---------------")
      logger.debug(endpoint)

      request = Typhoeus::Request.new(
        endpoint,
        method: :get
      )

      request.run
      res = request.response.body

      xml_doc = Nokogiri::XML(res)
      doc = REXML::Document.new(res)

      logger.debug("---------- Debug -----------")
      logger.debug(res)


      titems = xml_doc.xpath('itemId')


      dpath = doc.elements['findItemsAdvancedResponse/searchResult']

      spath = dpath.elements['item[' + String(rank) + ']']
      if spath != nil then
        logger.debug("Item Found")
        title = spath.elements['title'].text
        itemid = spath.elements['itemId'].text
        price = spath.elements['sellingStatus/convertedCurrentPrice'].text
        condi = spath.elements['condition/conditionDisplayName'].text
        ur = spath.elements['viewItemURL'].text
        ship = spath.elements['shippingInfo/handlingTime'].text
      else
        logger.debug("no item")
        title = "該当なし"
        itemid = ""
        price = ""
        condi = ""
        ur = ""
        ship = ""
      end
      logger.debug(title)

      buf = [
        query[0],
        query[1],
        query[2],
        price,
        title,
        ur,
        condi,
        ship,
        itemid
      ]
      render json:buf
    end
  end

  def save
    logger.debug("===================")
    logger.debug("Start save process")
    if request.post? then
      logger.debug(params[:search_condition])
      @condition = SearchCondition.find_or_initialize_by(user: current_user.email)
      @condition.update(user_params)
    else request.patch?
      @condition = SearchCondition.find_or_initialize_by(user: current_user.email)
      @condition.update(user_params)
    end
    redirect_to items_show_path
  end

  def update
    logger.debug("===================")
    @user = current_user.email
    search_user = @user + "_detail"
    if request.post? then
      logger.debug(params[:search_condition])

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/get.html.erb

<div class="bg-warning" style="align-items: center;">
  <h1 style="padding: 10px;">eBay詳細検索ページ</h1>
</div>
<h4>ログイン中：<%= @user %><%= link_to '通常検索', items_show_path, method: :get, style: 'margin-left: 16pt;' %><%= link_to 'トップページ', apps_show_path, method: :get, style: 'margin-left: 16pt;' %><%= link_to '管理者専用', rails_admin_path, method: :get, style: 'margin-left: 16pt;' %><%= link_to 'ログアウト', destroy_user_session_path, method: :get, style: 'margin-left: 16pt;' %></h4>
<br>

<ul class="nav nav-tabs" role="tablist">
  <li class="active" role="presentation">
    <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">1.検索条件の設定</a>
  </li>
  <li role="presentation">
    <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">2.キーワードの入力</a>
  </li>
  <li role="presentation">
    <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab">3.検索結果の確認</a>
  </li>
</ul>

<br>
<div class="tab-content">
  <div class="tab-pane active" id="tab_a" role="tabpanel">
    <div class="row">
      <div class="col-md-12">
        <p>検索条件の基本設定</p>
      </div>
    </div>
    <%= form_for(@condition, url: '/items/update', method: :post, html:{class:'form-horizontal'} ) do |f| %>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_app_id">eBayAppID</label>
        <div class="col-md-8">
          <%= f.text_field(:app_id, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_low_price">最低価格($)</label>
        <div class="col-md-8">
          <%= f.text_field(:low_price, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_high_price">最高価格($)</label>
        <div class="col-md-8">
          <%= f.text_field(:high_price, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_category_id">カテゴリーID</label>
        <div class="col-md-8">
          <%= f.select :category_id, @category_group, {}, {class:'form-control'} %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_item_condition">商品状態</label>
        <div class="col-md-8">
          <%= f.select :item_condition, @condition_group, {}, {class:'form-control'} %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_sales_type">販売形式</label>
        <div class="col-md-8">
          <%= f.select :sales_type, @sales_group, {}, {class:'form-control'} %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_handling_time">最大出荷期間 ※1以上の数字を入力</label>
        <div class="col-md-8">
          <%= f.text_field(:handling_time, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_rank">価格の順位</label>
        <div class="col-md-8">
          <%= f.text_field(:rank, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-4">
        <label class="col-md-4 control-label" for="search_condition_score">セラーの評価</label>
        <div class="col-md-8">
          <%= f.text_field(:score, class:'form-control') %>
        </div>
      </div>
      <div class="form-group col-md-5">
        <div class="col-md-1">
          <%= hidden_field_tag :user, @search_user %>
        </div>

          <%= f.submit('保存する', class:'btn btn-primary') %>

      </div>
    <% end %>
  </div>

  <div class="tab-pane" id="tab_b" role="tabpanel">
    <div class="row">
      <div class="col-md-12">
        <%= form_with url: items_get_path, method: :post do |form| %>
          <div class="form-inline">
            <label for="search_keyword">検索キーワード：</label>
            <%= text_field_tag :search_keyword, @search_keyword, class: 'form-control', style: 'width: 450px;' %>
            <%= form.submit '検索開始', class: 'btn btn-primary', style: 'margin-left: 10pt;' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="tab-pane" id="tab_c" role="tabpanel">
    <div class="row">
      <div class="col-md-12">
        <p>処理状況：<%= @status %></p>
        <p>取得条件</p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>取得日時</th>
              <th>キーワード</th>
              <th>カテゴリID</th>
              <th>最低価格</th>
              <th>最高価格</th>
            </tr>
          </thead>
          <tbody>
            <% if @search_group != nil then %>
            <tr>
              <td><%= @search_group.created_at.strftime("%Y/%m/%d %H:%M") %></td>
              <td><%= @search_group.query %></td>
              <td><%= @search_group.category_id %></td>
              <td><%= @search_group.low_price %></td>
              <td><%= @search_group.high_price %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <br>
      <div class="col-md-12">
        <%= form_with url: items_download_path(format: :csv), method: :post do |form| %>
          <%= submit_tag 'ダウンロード', class: 'btn btn-primary', style: 'margin-right: 10pt;' %>
          <label class="checkbox-inline"><input type="checkbox" name="item_id" value="1" id="chk_id" checked />商品ID</label>
          <label class="checkbox-inline"><input type="checkbox" name="title" value="1" id="chk_title" checked />商品名</label>
          <label class="checkbox-inline"><input type="checkbox" name="item_url" value="1" id="chk_url" checked />商品URL</label>
          <label class="checkbox-inline"><input type="checkbox" name="price" value="1" id="chk_sprice" checked />販売価格</label>
          <label class="checkbox-inline"><input type="checkbox" name="condition" value="1" id="chk_cond" checked />コンディション</label>
          <label class="checkbox-inline"><input type="checkbox" name="shipping" value="1" id="chk_ship" checked />配送期間</label>
          <label class="checkbox-inline"><input type="checkbox" name="specs" value="1" id="chk_ship" checked />Item Spec</label>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.addEventListener('DOMContentLoaded', function() {

    $(document).ready(function() {
    // #(ハッシュ)指定されたタブを表示する
      var hashTabName = document.location.hash;
      if (hashTabName) {
        $('.nav-tabs a[href="' + hashTabName + '"]').tab('show');
      }
    });

    //タブ切り替え時にリロード

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      var activated_tab = e.target // activated tab
      var previous_tab = e.relatedTarget // previous tab
      keyword_handsontable.render();
      result_handsontable.render();
    })

  })

  function formatDate (date, format) {
    format = format.replace(/yyyy/g, date.getFullYear());
    format = format.replace(/MM/g, ('0' + (date.getMonth() + 1)).slice(-2));
    format = format.replace(/dd/g, ('0' + date.getDate()).slice(-2));
    format = format.replace(/HH/g, ('0' + date.getHours()).slice(-2));
    format = format.replace(/mm/g, ('0' + date.getMinutes()).slice(-2));
    format = format.replace(/ss/g, ('0' + date.getSeconds()).slice(-2));
    format = format.replace(/SSS/g, ('00' + date.getMilliseconds()).slice(-3));
    return format;
  };
</script>

app/views/items/search.html.erb
<h1>Items#search</h1>
<p>Find me in app/views/items/search.html.erb</p>