config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  get 'items/get'
  post 'items/get'
  get 'items/download'
  post 'items/download'
  get 'items' => 'items#show'
  get 'items/show'
  post 'items/show'
  get 'items/delete'
  post 'items/load'
  post 'items/update'

  post 'items/save'
  patch 'items/save'
  get 'items/save' => 'items#show'

  get 'items/search'
  post 'items/search'

  root to: 'apps#show'
  get 'apps/show'
  post 'stocks/delete'
  get 'stocks/show'
  post 'stocks/show'
  post 'stocks/update'
  get 'stocks/search'
  post 'stocks/search'
  post 'stocks/import'
  get 'stocks/export'
  post 'stocks/export'
  post 'stocks/load'
  post 'stocks/setpw'
  get 'stocks/export.csv'  => 'stocks#show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, at: "/resque"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/apps/show.html.erb
<div class="bg-success" style="align-items: center;">
  <h1 style="padding: 10px;">アプリケーションの管理&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>product by <a href="http://ec-merchant.com" target="_blank">ec-merchant.com</a></small></h1>
</div>
<h4>ログイン中：<%= @user %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'ログアウト', destroy_user_session_path, method: :get %>&nbsp;&nbsp;&nbsp;<%= link_to '管理者専用', rails_admin_path, method: :get %></h4>
<br>
<br>
<h2><%= link_to '在庫管理表はこちら', stocks_show_path, method: :get %></h2>
<h2><%= link_to 'リサーチツールはこちら', items_show_path, method: :get %></h2>